DROP TABLE if exists larku.student_scheduledclass;

DROP TABLE if exists larku.scheduledclass;

DROP TABLE if exists larku.course;

DROP TABLE if exists larku.student;


CREATE TABLE student (
		ID INT(11) NOT NULL AUTO_INCREMENT,
		NAME VARCHAR(255) NOT NULL,
		PHONENUMBER VARCHAR(20),
		STATUS VARCHAR(20),
	  CONSTRAINT student_pk PRIMARY KEY (id)
	);
	
CREATE TABLE course (
		ID INT NOT NULL AUTO_INCREMENT,
		CODE VARCHAR(20),
		CREDITS DOUBLE NOT NULL,
		TITLE VARCHAR(255),
	  CONSTRAINT course_pk PRIMARY KEY (id)
	);

CREATE TABLE scheduledclass (
		ID INT NOT NULL AUTO_INCREMENT,
		ENDDATE VARCHAR(20),
		STARTDATE VARCHAR(20),
		COURSE_ID INTEGER,
	  CONSTRAINT class_pk PRIMARY KEY (id)
	);

CREATE TABLE larku.student_scheduledclass (
		STUDENTS_ID INTEGER NOT NULL,
		CLASSES_ID INTEGER NOT NULL
	);

CREATE UNIQUE INDEX SQL150211090953900 ON larku.course (ID ASC);

CREATE INDEX SQL150211090954080 ON larku.student_scheduledclass (CLASSES_ID ASC);

CREATE INDEX SQL150211090953990 ON larku.scheduledclass (COURSE_ID ASC);

CREATE UNIQUE INDEX SQL150211090953920 ON larku.scheduledclass (ID ASC);

CREATE UNIQUE INDEX SQL150211090953950 ON larku.student (ID ASC);

CREATE INDEX SQL150211090954040 ON larku.student_scheduledclass (STUDENTS_ID ASC);

-- ALTER TABLE larku.COURSE ADD CONSTRAINT SQL150211090953900 PRIMARY KEY (ID);

-- ALTER TABLE larku.SCHEDULEDCLASS ADD CONSTRAINT SQL150211090953920 PRIMARY KEY (ID);

-- ALTER TABLE larku.STUDENT ADD CONSTRAINT SQL150211090953950 PRIMARY KEY (ID);

ALTER TABLE larku.student_scheduledclass ADD CONSTRAINT FK318CA38F83AAB40 FOREIGN KEY (CLASSES_ID)
	REFERENCES larku.scheduledclass (ID);

ALTER TABLE larku.student_scheduledclass ADD CONSTRAINT FK318CA38F5E4D1BDC FOREIGN KEY (STUDENTS_ID)
	REFERENCES larku.student (ID);

ALTER TABLE larku.student_scheduledclass ADD CONSTRAINT NEW_UNIQUE UNIQUE (STUDENTS_ID, CLASSES_ID);	

ALTER TABLE larku.scheduledclass ADD CONSTRAINT FKE64C28EBD735B77B FOREIGN KEY (COURSE_ID)
	REFERENCES larku.course (ID);
	


	